default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV.fetch('DATABASE_PORT') { 3306 } %>
  username: <%= ENV.fetch('DATABASE_USERNAME') { 'root' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { '' } %>

development:
  <<: *default
  database: circleci_test_development

test:
  <<: *default
  database: circleci_test_test

production:
  <<: *default
  database: circleci_test_production
  username: circleci_test
  password: <%= ENV['CIRCLECI_TEST_DATABASE_PASSWORD'] %>
